version: '3.8'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Weather
    environment:
      - FLASK_ENV=production
      - UPLOAD_FOLDER=/app/uploads
    ports:
      - "1199:1199"
    volumes:
      - ./uploads:/app/uploads
      - ./static:/app/static
      - ./data:/app/data
      - ./instance:/app/instance
    restart: unless-stopped